                st.write("Heat Ratio")
                fig1 = plt.figure(figsize=(15, 8))
                plt.hist(Daily_RET, bins=50, label="Daily Return", color="salmon", rwidth=1)
                plt.legend()
                plt.xticks(np.arange(-0.1, 0.11,0.01), ['{:.1%}'.format(x) for x in np.arange(-0.1, 0.11,0.01)])
                plt.margins(x=-0.1, y=0)
                st.pyplot(fig1)
